CREATE TABLE [dbo].[CovidVaccinations] (
    [iso_code]                              NVARCHAR (50) NOT NULL,
    [continent]                             NVARCHAR (50) NULL,
    [location]                              NVARCHAR (50) NULL,
    [date]                                  DATE          NULL,
    [new_tests]                             BIGINT        NULL,
    [total_tests]                           BIGINT        NULL,
    [total_tests_per_thousand]              FLOAT (53)    NULL,
    [new_tests_per_thousand]                FLOAT (53)    NULL,
    [new_tests_smoothed]                    BIGINT        NULL,
    [new_tests_smoothed_per_thousand]       FLOAT (53)    NULL,
    [positive_rate]                         FLOAT (53)    NULL,
    [tests_per_case]                        FLOAT (53)    NULL,
    [tests_units]                           NVARCHAR (50) NULL,
    [total_vaccinations]                    BIGINT        NULL,
    [people_vaccinated]                     BIGINT        NULL,
    [people_fully_vaccinated]               BIGINT        NULL,
    [new_vaccinations]                      BIGINT        NULL,
    [new_vaccinations_smoothed]             BIGINT        NULL,
    [total_vaccinations_per_hundred]        FLOAT (53)    NULL,
    [people_vaccinated_per_hundred]         FLOAT (53)    NULL,
    [people_fully_vaccinated_per_hundred]   FLOAT (53)    NULL,
    [new_vaccinations_smoothed_per_million] BIGINT        NULL,
    [stringency_index]                      FLOAT (53)    NULL,
    [population]                            BIGINT        NULL,
    [population_density]                    FLOAT (53)    NULL,
    [median_age]                            FLOAT (53)    NULL,
    [aged_65_older]                         FLOAT (53)    NULL,
    [aged_70_older]                         FLOAT (53)    NULL,
    [gdp_per_capita]                        FLOAT (53)    NULL,
    [extreme_poverty]                       FLOAT (53)    NULL,
    [cardiovasc_death_rate]                 FLOAT (53)    NULL,
    [diabetes_prevalence]                   FLOAT (53)    NULL,
    [female_smokers]                        FLOAT (53)    NULL,
    [male_smokers]                          FLOAT (53)    NULL,
    [handwashing_facilities]                FLOAT (53)    NULL,
    [hospital_beds_per_thousand]            FLOAT (53)    NULL,
    [life_expectancy]                       FLOAT (53)    NULL,
    [human_development_index]               FLOAT (53)    NULL,
    [excess_mortality]                      FLOAT (53)    NULL
);


GO

